language: go
sudo: false

go:
- 1.11.x
- tip

matrix:
  fast_finish: true
  allow_failures:
  - go: tip

before_install:
- go get golang.org/x/lint/golint
- go get honnef.co/go/tools/cmd/staticcheck
- go get -u golang.org/x/tools/cmd/goimports
- go get -u github.com/golang/dep/cmd/dep
- make dep

script:
- make verify

cache:
  directories:
    - vendor