language: go
sudo: false

go:
- 1.12.x
- master

matrix:
  fast_finish: true
  allow_failures:
  - go: master

before_install:
- make init dep

script:
- make verify

cache:
  directories:
    - vendor
